### PR TITLE
Automations

### PR DESCRIPTION
**Pull request by yuval-yssak**

### CODE REVIEW

**Comment by yuval-yssak** [comment]
@claire-matlak Please take a look at these changes.
If this works for you, you can merge this PR (pull request) into main with the green button and it should work.

**Comment by claire-matlak** [comment]
@yuval-yssak Thank you for the changes. Just merged the commit. The HK app has not crashed and it still shows flight times for those with the old format (no lost flight info), although it still does not display the `standardFlightTIme` from `arrival-time` for flight times in the new format. 

With bed arrangement, it stopped showing the previous format but doesn't yet show the new format. The idea behind the new format is to create a "blank" option to clear the question for the instances when guests say "king bed" but they're staying in a different room type. (Change from radio dial to drop-down menu)

**Comment by claire-matlak** [comment]
@yuval-yssak Now that the app synced the changes, all of the old-format flight times have disappeared. The new-format flight times do appear now. (Hooray!) I don't have a script ready to do the conversion, so I'll adjust them manually for today and the next couple of days.  

I made a small adjustment in the syntax for the bed arrangement. With the synchronization, that is now working, too. (Double hooray!)

**Comment by yuval-yssak** [comment]
Ah... Oops.
That's what happens when I push code that I don't test....

Thank you for finding the error.

**Pull request merged**
